// Описание погоды при получении данных из api.openweathermap.org на английском:

export const conditionDescription = (props) => {
    const descriptionEN = [
        'light shower snow',
        'heavy shower snow',
        'fog',
        'overcast clouds',
        'clear sky',
        'few clouds',
        'scattered clouds',
        'broken clouds',
        'shower rain',
        'rain',
        'thunderstorm',
        'snow',
        'mist',
        'thunderstorm with light rain',
        'thunderstorm with rain',
        'thunderstorm with heavy rain',
        'light thunderstorm',
        'thunderstorm',
        'heavy thunderstorm',
        'ragged thunderstorm',
        'thunderstorm with light drizzle',
        'thunderstorm with drizzle',
        'thunderstorm with heavy drizzle',
        'light intensity drizzle',
        'drizzle',
        'heavy intensity drizzle',
        'light intensity drizzle rain',
        'drizzle rain',
        'heavy intensity drizzle rain',
        'shower rain and drizzle',
        'heavy shower rain and drizzle',
        'shower drizzle',
        'light rain',
        'moderate rain',
        'heavy intensity rain',
        'very heavy rain',
        'extreme rain',
        'freezing rain',
        'light intensity shower rain',
        'shower rain',
        'heavy intensity shower rain',
        'ragged shower rain',
        'light snow',
        'Snow',
        'Heavy snow',
        'Sleet',
        'Light shower sleet',
        'Shower sleet',
        'Light rain and snow',
        'Rain and snow',
        'Light shower snow',
        'Shower snow',
        'Heavy shower snow'
    ];

    const descriptionRU = [
        'небольшой снегопад',
        'сильный снегопад',
        'туман',
        'пасмурно',
        'чистое небо',
        'небольшая облачность',
        'переменная облачность',
        'облачно',
        'ливень',
        'дождь',
        'гроза',
        'снег',
        'туман',
        'кратковременная гроза',
        'гроза',
        'гроза с сильным дождём',
        'лёгкая гроза',
        'гроза',
        'сильная гроза',
        'местами грозы',
        'гроза с небольшим дождём',
        'гроза с моросящим дождём',
        'гроза с сильно моросящим дождём',
        'слабо моросящий дождь',
        'моросящий дождь',
        'сильно моросящий дождь',
        'слабо моросящий дождь',
        'моросящий дождь',
        'сильно моросящий дождь',
        'кратковременные моросящие дожди',
        'проливной кратковременный дождь',
        'плотно моросящий дождь',
        'небольшой дождь',
        'умеренный дождь',
        'сильный дождь',
        'очень сильный дождь',
        'ливень',
        'ледяной дождь',
        'умеренный дождь',
        'проливной дождь',
        'сильный ливень',
        'переменный ливень',
        'небольшой снегопад',
        'снег',
        'сильный снегопад',
        'мокрый снег',
        'небольшой дождь со снегом',
        'слякоть, дождь со снегом',
        'переменный дождь со снегом',
        'дождь со снегом',
        'небольшой снег',
        'непрерывный снегопад',
        'обильный снегопад'
    ]; 

    let selectDescription = descriptionEN.indexOf(props.condition);
    
    return descriptionRU[selectDescription];
};

// Вставить функцию в ThisDayDatails/index.jsx, и добавить результат в item.cloudy:
// value: conditionDescription(forecastData),
